name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: Azure/docker-login@v1
      with:
        login-server: docker.talam.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t docker.talam.io/matrimandir.org:${{ github.sha }}
        docker push docker.talam.io/matrimandir.org:${{ github.sha }}
    - uses: Azure/k8s-set-context@v1
      with:
        method:  service-account
        k8s-url:  https://135.181.34.108:16443
        k8s-secret: ${{ secrets.TALAM_K8S_SECRET }}
        id:  setcontext

    - uses: Azure/k8s-create-secret@v1
      with:
        secret-name: talam-docker-registry-secret
        container-registry-url: docker.talam.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}


    - uses: Azure/k8s-create-secret@v1
      with:
        secret-type: 'generic'
        namespace: 'default'
        secret-name: matrimandir-app-secret
        arguments: --from-literal=DATABASE_URL=${{ secrets.DATABASE_URL }} --from-literal=SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} --from-literal=APP_DOMAIN=${{ secrets.APP_DOMAIN }} --from-literal=APP_BASE_DOMAIN=${{ secrets.APP_BASE_DOMAIN }} --from-literal=OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }} --from-literal=OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }} --from-literal=OAUTH_LOGIN_URL=${{ secrets.OAUTH_LOGIN_URL }} --from-literal=S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} --from-literal=S3_HOST=${{ secrets.S3_HOST }} --from-literal=S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} --from-literal=S3_ACCESS_SECRET=${{ secrets.S3_ACCESS_SECRET }} --from-literal=MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}

    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
