name: Build for deployment
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
         - uses: actions/checkout@master
          - uses: Azure/k8s-deploy@v1
            with:
              manifests: |
                manifests/deployment.yml
                manifests/service.yml
                manifests/ingress.yml
              images: |
                docker.talam.io/matrimandir.org:${{ github.sha }}
              imagepullsecrets: |
                talam-docker-registry-secret
